<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/creation_of_series_and_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas

In [1]:
import numpy as np
import pandas as pd

series

In [2]:
ser1=pd.Series([1,2,3,4,5])
ser1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
ser1=pd.Series([10,20,30,40,50])
ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
arr=np.array([100,200,300,400,500])
arr

array([100, 200, 300, 400, 500])

what is the memory location of first elemen 100

In [7]:
arr.ctypes.data

261028928

In [6]:
ser2=pd.Series(arr)
ser2

0    100
1    200
2    300
3    400
4    500
dtype: int64

To aee the underlying array of a series use attributes .values

In [8]:
ser2.values

array([100, 200, 300, 400, 500])

In [9]:
ser2.values.ctypes.data

261028928

All the values of series are stored in the form of ndarray

In [10]:
dct={'a':10,'b':20,'c':30,'d':40}
dct

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [11]:
ser3=pd.Series(dct)
ser3

a    10
b    20
c    30
d    40
dtype: int64

by creating a series with dictionary,no need to assign explict indices manually.

-keys of a dictionary are considered as indlices od series

In [14]:
#change the datatype from 'int64' to 'uint8'
ser1=pd.Series([10,20,30,40,50],dtype='uint8')
ser1

0    10
1    20
2    30
3    40
4    50
dtype: uint8

In [15]:

ser1=pd.Series([10,20,30,40,50],dtype='uint8',index=['one','two','three','four','five'])
ser1

one      10
two      20
three    30
four     40
five     50
dtype: uint8

In [18]:
ser1=pd.Series([10,20,30,40,50],dtype='uint8',index= [100,200,300,400,500])
ser1

100    10
200    20
300    30
400    40
500    50
dtype: uint8

in explict indices for series or dataframe,duplicates are allowed

In [19]:
#assign a name to series
ser1=pd.Series([10,20,30,40,50],dtype='uint8',index=['one','two','three','four','five'],name='Numbers')
ser1

one      10
two      20
three    30
four     40
five     50
Name: Numbers, dtype: uint8

In [21]:
ser1.dtype

dtype('uint8')

In [22]:
ser1.name

'Numbers'

In [23]:
ser1.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

How to change 'dtype','name' and 'index' after creation

In [24]:
ser2=pd.Series(np.arange(1,7))
ser2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

To change datatype use a method.astype(dtype)

In [25]:
ser2.astype('uint8')

0    1
1    2
2    3
3    4
4    5
5    6
dtype: uint8

In [26]:
ser2.dtype

dtype('int64')

In [27]:
ser2=ser2.astype('uint8')
ser2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: uint8

In [29]:
ser2.dtype

dtype('uint8')

In [30]:
ser2.name

In [31]:
print(ser2.name)

None

In [32]:
ser2.name='NUM'
ser2

0    1
1    2
2    3
3    4
4    5
5    6
Name: NUM, dtype: uint8

In [33]:
ser2.index

RangeIndex(start=0, stop=6, step=1)

In [34]:
ser2.index=['a','b','c','d','e','f']
ser2

a    1
b    2
c    3
d    4
e    5
f    6
Name: NUM, dtype: uint8

DataFrame

In [35]:
df1=pd.DataFrame([1,2,3,4,5])
df1

   0
0  1
1  2
2  3
3  4
4  5

In [36]:
ser2.shape

(6,)

In [37]:
df1.shape

(5, 1)

Default every dataframe is 2d

In [38]:
df1=pd.DataFrame((1,2,3,4,5))
df1

   0
0  1
1  2
2  3
3  4
4  5

In [39]:
df1=pd.DataFrame(np.arange(1,7))
df1

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [40]:
df1=pd.DataFrame(np.arange(1,21).reshape(4,5))
df1

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [42]:
df1=pd.DataFrame([[1,2,3,],[4,5,6],[7,8,9]])
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [43]:
#nested tuple
df1=pd.DataFrame(((1,2,3),(4,5,6),(7,8,9)))
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

possible

.a list of tuples
.a tuple of lists

In [44]:
df1=pd.DataFrame([['a','b','c'],['d','e','f']])
df1

   0  1  2
0  a  b  c
1  d  e  f

In [45]:
dct={'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}
dct

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

In [47]:
dct={'a':(1,2,3),'b':(4,5,6),'c':(7,8,9)}
dct

{'a': (1, 2, 3), 'b': (4, 5, 6), 'c': (7, 8, 9)}

popular ways

.nested dictionaries

In [49]:
dct2={'a':{'one':1,'two':2},'b':{'one':10,'two':20,'three':30},'c':{'one':100}}
dct2

{'a': {'one': 1, 'two': 2},
 'b': {'one': 10, 'two': 20, 'three': 30},
 'c': {'one': 100}}

In [52]:
df3=pd.DataFrame(dct2)
df3

         a   b      c
one    1.0  10  100.0
two    2.0  20    NaN
three  NaN  30    NaN

with nested dict.no need to provide row and column indices manually

-keys of outside dict-columns(column index)of dataframe

-keys of inside dict-index(row imdex)of dataframe

In [54]:
#dict of series
ser1=pd.Series(np.arange(1,7),index=list('abcdef'))
ser1=pd.Series(np.arange(7,13),index=list('abcdef'))
ser1=pd.Series(np.arange(13,19),index=list('abcdef'))
ser1,ser2,ser3

(a    13
 b    14
 c    15
 d    16
 e    17
 f    18
 dtype: int64,
 a    1
 b    2
 c    3
 d    4
 e    5
 f    6
 Name: NUM, dtype: uint8,
 a    10
 b    20
 c    30
 d    40
 dtype: int64)

In [55]:
dct4={'col1':ser1,'col2':ser2,'col3':ser3}
dct4

{'col1': a    13
 b    14
 c    15
 d    16
 e    17
 f    18
 dtype: int64,
 'col2': a    1
 b    2
 c    3
 d    4
 e    5
 f    6
 Name: NUM, dtype: uint8,
 'col3': a    10
 b    20
 c    30
 d    40
 dtype: int64}

In [56]:
df4=pd.DataFrame(dct4)
df4

   col1  col2  col3
a    13     1  10.0
b    14     2  20.0
c    15     3  30.0
d    16     4  40.0
e    17     5   NaN
f    18     6   NaN

In [58]:
df4.values

array([[13.,  1., 10.],
       [14.,  2., 20.],
       [15.,  3., 30.],
       [16.,  4., 40.],
       [17.,  5., nan],
       [18.,  6., nan]])

In [59]:
df5=pd.DataFrame(np.arange(1,26).reshape(5,5))
df5

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [60]:
df5=pd.DataFrame(np.arange(1,26).reshape(5,5),index=['r1','r2','r3','r4','r5'])
df5

     0   1   2   3   4
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20
r5  21  22  23  24  25

In [61]:
df5=pd.DataFrame(np.arange(1,26).reshape(5,5),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4','c5'])
df5

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20
r5  21  22  23  24  25

in a dataframe every column may assume different datatype,based on the variable it assumes

-to check 'dtype and assign 'dtype use '.dtypes'

-.dtypes always returns a series with values

In [63]:
df5.dtypes

c1    int64
c2    int64
c3    int64
c4    int64
c5    int64
dtype: object

In [64]:
#modify the column,row
df5=pd.DataFrame(np.arange(1,26).reshape(5,5),
                 index=['r1','r2','r3','r4','r5'],
                 columns=['c1','c2','c3','c4','c5'],
                 dtype='uint8')
df5

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20
r5  21  22  23  24  25

In [65]:
#change the datatype of every columns in dataframe
df5.astype({'c1':'uint8','c2':'uint16','c3':'uint32','c4':'uint64','c5':'int8'})
df5

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20
r5  21  22  23  24  25

In [66]:
df5.dtypes

c1    uint8
c2    uint8
c3    uint8
c4    uint8
c5    uint8
dtype: object

math operations on a series

In [67]:
ser1=pd.Series([1,2,3,4,5],index=list('abcde'))
ser2=pd.Series([10,20,30,40,50,60,70],index=list('cdefghi'))
ser1,ser2

(a    1
 b    2
 c    3
 d    4
 e    5
 dtype: int64,
 c    10
 d    20
 e    30
 f    40
 g    50
 h    60
 i    70
 dtype: int64)

In [68]:
display(ser1,ser2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

c    10
d    20
e    30
f    40
g    50
h    60
i    70
dtype: int64

like ndarray,operations and performed on element of series

In [69]:
ser1+ser2

a     NaN
b     NaN
c    13.0
d    24.0
e    35.0
f     NaN
g     NaN
h     NaN
i     NaN
dtype: float64