<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/eda_statictics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

08/09

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv(r'/content/cleaned_emp_data.csv')
data

     Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt          Team
0             0    Douglas    Male     8/6/93   90281.27   True     Marketing
1             1     Thomas    Male    3/31/96   61933.00   True            IT
2             3      Jerry  Female     3/4/05  138705.00   True       Finance
3             4      Larry    Male    1/24/98  101004.00   True            IT
4             5     Dennis    Male    4/18/87  115163.00  False         Legal
..          ...        ...     ...        ...        ...    ...           ...
927         995      Henry  Female   11/23/14  132483.00  False  Distribution
928         996    Phillip    Male    1/31/84   42392.00  False       Finance
929         997    Russell    Male    5/20/13   96914.00  False       Product
930         998      Larry    Male    4/20/13   60500.00  False  Business Dev
931         999     Albert    Male    5/15/12  129949.00   True         Sales

[932 rows x 7 columns]

**what if we want to isolate the employee who bwlong to either the sales.legal,or marketing team?**

In [ ]:
(data.Team=='Marketing')|(data.Team=='Legal')|(data.Team=='Sales')

0       True
1      False
2      False
3      False
4       True
       ...
927    False
928    False
929    False
930    False
931     True
Name: Team, Length: 932, dtype: bool

In [ ]:
data[(data.Team=='Marketing')|(data.Team=='Legal')|(data.Team=='Sales')]

     Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt       Team
0             0    Douglas    Male     8/6/93   90281.27   True  Marketing
4             5     Dennis    Male    4/18/87  115163.00  False      Legal
9            11      Julie  Female   10/26/97  102508.00   True      Legal
11           13       Gary    Male    1/27/08  109831.00  False      Sales
18           20       Lois  Female    4/22/95   64714.00   True      Legal
..          ...        ...     ...        ...        ...    ...        ...
918         986      Donna  Female   11/26/82   82871.00  False  Marketing
921         989     Justin  Female    2/10/91   38344.00  False      Legal
923         991       Rose  Female    8/25/02  134505.00   True  Marketing
926         994     George    Male    6/21/13   98874.00   True  Marketing
931         999     Albert    Male    5/15/12  129949.00   True      Sales

[263 rows x 7 columns]

Instead of writing conditions on

In [ ]:
(data.Team=='Marketing')|(data.Team=='Legal')|(data.Team=='Sales')

0       True
1      False
2      False
3      False
4       True
       ...
927    False
928    False
929    False
930    False
931     True
Name: Team, Length: 932, dtype: bool

In [ ]:
data[(data.Team=='Marketing')|(data.Team=='Legal')|(data.Team=='Sales')]

     Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt       Team
0             0    Douglas    Male     8/6/93   90281.27   True  Marketing
4             5     Dennis    Male    4/18/87  115163.00  False      Legal
9            11      Julie  Female   10/26/97  102508.00   True      Legal
11           13       Gary    Male    1/27/08  109831.00  False      Sales
18           20       Lois  Female    4/22/95   64714.00   True      Legal
..          ...        ...     ...        ...        ...    ...        ...
918         986      Donna  Female   11/26/82   82871.00  False  Marketing
921         989     Justin  Female    2/10/91   38344.00  False      Legal
923         991       Rose  Female    8/25/02  134505.00   True  Marketing
926         994     George    Male    6/21/13   98874.00   True  Marketing
931         999     Albert    Male    5/15/12  129949.00   True      Sales

[263 rows x 7 columns]

In [ ]:
data.Team.isin(['Sales','Marketing','Legal'])

0       True
1      False
2      False
3      False
4       True
       ...
927    False
928    False
929    False
930    False
931     True
Name: Team, Length: 932, dtype: bool

In [ ]:
data[data.Team.isin(['Sales','Marketing','Legal'])]

     Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt       Team
0             0    Douglas    Male     8/6/93   90281.27   True  Marketing
4             5     Dennis    Male    4/18/87  115163.00  False      Legal
9            11      Julie  Female   10/26/97  102508.00   True      Legal
11           13       Gary    Male    1/27/08  109831.00  False      Sales
18           20       Lois  Female    4/22/95   64714.00   True      Legal
..          ...        ...     ...        ...        ...    ...        ...
918         986      Donna  Female   11/26/82   82871.00  False  Marketing
921         989     Justin  Female    2/10/91   38344.00  False      Legal
923         991       Rose  Female    8/25/02  134505.00   True  Marketing
926         994     George    Male    6/21/13   98874.00   True  Marketing
931         999     Albert    Male    5/15/12  129949.00   True      Sales

[263 rows x 7 columns]

identify all employees with a salary between $80,000 and $ 90,000

In [ ]:
(data.Salary > 80000) &(data.Salary <90000)

0      False
1      False
2      False
3      False
4      False
       ...
927    False
928    False
929    False
930    False
931    False
Name: Salary, Length: 932, dtype: bool

In [ ]:
data[(data.Salary > 80000) &(data.Salary <90000)]

     Unnamed: 0 First Name  Gender Start Date   Salary   Mgmt         Team
17           19      Donna  Female    7/22/10  81014.0  False      Product
27           31      Joyce  Female    2/20/05  88657.0  False      Product
30           35    Theresa  Female   10/10/06  85182.0  False        Sales
39           45      Roger    Male    4/17/80  88010.0   True        Sales
47           54       Sara  Female    8/15/07  83677.0  False  Engineering
..          ...        ...     ...        ...      ...    ...          ...
865         930      Nancy  Female    9/10/01  85213.0   True    Marketing
888         956    Beverly  Female   10/17/86  80838.0  False  Engineering
895         963        Ann  Female    9/23/94  89443.0   True        Sales
917         985    Stephen  Female    7/10/83  85668.0  False        Legal
918         986      Donna  Female   11/26/82  82871.0  False    Marketing

[85 rows x 7 columns]

.Between(left,right,include)

-left< variable<right

1.left<var<right-salary>80000and <90000,inclusive='neither

2.left<=var<right-salary>= 80000  and <90000,inclusive='left'

3.left<var<=right -salary>80000 and <=90000,inclusive='right'

4.left<=var<=right-salary >=80000 and <=90000,inclusive='both'

In [12]:
data.Salary.between(80000,90000,inclusive='neither')

0      False
1      False
2      False
3      False
4      False
       ...
927    False
928    False
929    False
930    False
931    False
Name: Salary, Length: 932, dtype: bool

In [13]:
data[data.Salary.between(80000,90000,inclusive='neither')]

     Unnamed: 0 First Name  Gender Start Date   Salary   Mgmt         Team
17           19      Donna  Female    7/22/10  81014.0  False      Product
27           31      Joyce  Female    2/20/05  88657.0  False      Product
30           35    Theresa  Female   10/10/06  85182.0  False        Sales
39           45      Roger    Male    4/17/80  88010.0   True        Sales
47           54       Sara  Female    8/15/07  83677.0  False  Engineering
..          ...        ...     ...        ...      ...    ...          ...
865         930      Nancy  Female    9/10/01  85213.0   True    Marketing
888         956    Beverly  Female   10/17/86  80838.0  False  Engineering
895         963        Ann  Female    9/23/94  89443.0   True        Sales
917         985    Stephen  Female    7/10/83  85668.0  False        Legal
918         986      Donna  Female   11/26/82  82871.0  False    Marketing

[85 rows x 7 columns]

use .between() with string data too

extract all employees whose first names started with the letter 'R'

In [15]:
data['First Name'].between('R','S')

0      False
1      False
2      False
3      False
4      False
       ...
927    False
928    False
929     True
930    False
931    False
Name: First Name, Length: 932, dtype: bool

In [16]:
data[data['First Name'].between('R','S')]

     Unnamed: 0 First Name  Gender Start Date    Salary   Mgmt          Team
5             6       Ruby  Female    8/17/87   65476.0   True       Product
31           36     Rachel  Female    2/16/09  142032.0  False  Business Dev
39           45      Roger    Male    4/17/80   88010.0   True         Sales
59           67     Rachel  Female    8/16/99   51178.0   True       Finance
70           78      Robin  Female     6/4/83  114797.0   True         Sales
..          ...        ...     ...        ...       ...    ...           ...
905         973    Russell    Male    5/10/13  137359.0  False  Business Dev
914         982       Rose  Female     4/6/82   91411.0   True            HR
922         990      Robin  Female    7/24/87  100765.0   True            IT
923         991       Rose  Female    8/25/02  134505.0   True     Marketing
929         997    Russell    Male    5/20/13   96914.0  False       Product

[88 rows x 7 columns]

In [17]:
data

     Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt          Team
0             0    Douglas    Male     8/6/93   90281.27   True     Marketing
1             1     Thomas    Male    3/31/96   61933.00   True            IT
2             3      Jerry  Female     3/4/05  138705.00   True       Finance
3             4      Larry    Male    1/24/98  101004.00   True            IT
4             5     Dennis    Male    4/18/87  115163.00  False         Legal
..          ...        ...     ...        ...        ...    ...           ...
927         995      Henry  Female   11/23/14  132483.00  False  Distribution
928         996    Phillip    Male    1/31/84   42392.00  False       Finance
929         997    Russell    Male    5/20/13   96914.00  False       Product
930         998      Larry    Male    4/20/13   60500.00  False  Business Dev
931         999     Albert    Male    5/15/12  129949.00   True         Sales

[932 rows x 7 columns]

In [20]:
data[~data.Team.duplicated()]

    Unnamed: 0 First Name  Gender Start Date     Salary   Mgmt          Team
0            0    Douglas    Male     8/6/93   90281.27   True     Marketing
1            1     Thomas    Male    3/31/96   61933.00   True            IT
2            3      Jerry  Female     3/4/05  138705.00   True       Finance
4            5     Dennis    Male    4/18/87  115163.00  False         Legal
5            6       Ruby  Female    8/17/87   65476.00   True       Product
6            8     Angela  Female   11/22/05   95570.00   True   Engineering
7            9    Frances  Female     8/8/02  139852.00   True  Business Dev
10          12    Brandon    Male    12/1/80  112807.00   True            HR
11          13       Gary    Male    1/27/08  109831.00  False         Sales
34          40    Michael    Male   10/10/08   99283.00   True  Distribution

In [21]:
data[data.Team.duplicated()]

     Unnamed: 0 First Name  Gender Start Date    Salary   Mgmt          Team
3             4      Larry    Male    1/24/98  101004.0   True            IT
8            10     Louise  Female    8/12/80   63241.0   True            IT
9            11      Julie  Female   10/26/97  102508.0   True         Legal
12           14   Kimberly  Female    1/14/99   41426.0   True       Finance
13           15    Lillian  Female     6/5/16   59414.0  False       Product
..          ...        ...     ...        ...       ...    ...           ...
927         995      Henry  Female   11/23/14  132483.0  False  Distribution
928         996    Phillip    Male    1/31/84   42392.0  False       Finance
929         997    Russell    Male    5/20/13   96914.0  False       Product
930         998      Larry    Male    4/20/13   60500.0  False  Business Dev
931         999     Albert    Male    5/15/12  129949.0   True         Sales

[922 rows x 7 columns]

In [22]:
data[~data.Team.duplicated(keep='last')]

     Unnamed: 0 First Name  Gender Start Date    Salary   Mgmt          Team
920         988      Alice  Female    10/5/04   47638.0  False            HR
921         989     Justin  Female    2/10/91   38344.0  False         Legal
922         990      Robin  Female    7/24/87  100765.0   True            IT
925         993       Tina  Female    5/15/97   56450.0   True   Engineering
926         994     George    Male    6/21/13   98874.0   True     Marketing
927         995      Henry  Female   11/23/14  132483.0  False  Distribution
928         996    Phillip    Male    1/31/84   42392.0  False       Finance
929         997    Russell    Male    5/20/13   96914.0  False       Product
930         998      Larry    Male    4/20/13   60500.0  False  Business Dev
931         999     Albert    Male    5/15/12  129949.0   True         Sales

In [27]:
import numpy as np
import pandas as pd
loan=pd.read_csv(r'/content/loandata.csv')
loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y

In [28]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [29]:
loan.describe() #description of only numeric variables

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [30]:
loan.describe(include='all')

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,614,601,611,599,614,582,614.000000,614.000000,592.000000,600.00000,564.000000,614,614
unique,614,2,2,4,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP002317,Male,Yes,0,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,489,398,345,480,500,NaN,NaN,NaN,NaN,NaN,233,422
mean,NaN,NaN,NaN,NaN,NaN,NaN,5403.459283,1621.245798,146.412162,342.00000,0.842199,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,6109.041673,2926.248369,85.587325,65.12041,0.364878,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,0.000000,9.000000,12.00000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2877.500000,0.000000,100.000000,360.00000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3812.500000,1188.500000,128.000000,360.00000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,5795.000000,2297.250000,168.000000,360.00000,1.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,81000.000000,41667.000000,700.000000,480.00000,1.000000,NaN,NaN