<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/java_Practice/blob/main/series_with_hetergenous.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

01/09

In [3]:
import numpy as np
import pandas as pd

In [4]:
ser1=pd.Series([1,2.3,True,'Hello'])
ser2=pd.Series([5,2.5,False,'World'])
ser1+ser2

0             6
1           4.8
2             1
3    HelloWorld
dtype: object

series:indexing and slicing

In [6]:
ser1=pd.Series([10,20,30,40,50])
ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
#elements 30 from series
ser1[2]

np.int64(30)

In [8]:
#extract elements 20,30 and 40
ser1[1:3+1]

1    20
2    30
3    40
dtype: int64

In [9]:
#get elements 10,20, and 50
ser1[0::2]

0    10
2    30
4    50
dtype: int64

In [12]:
#get the elements 10,20 and 40
ser1[[0,1,3]]

0    10
1    20
3    40
dtype: int64

In [13]:
#get the elements divisible by 4
ser1[[False,True,False,True,False]]

1    20
3    40
dtype: int64

In [14]:
ser1[ser1%4==0]

1    20
3    40
dtype: int64

In [15]:
ser2=pd.Series([1,2,3,4,5,6],index=list('abcdef'),dtype='uint8',name='NUM')
ser2

a    1
b    2
c    3
d    4
e    5
f    6
Name: NUM, dtype: uint8

In [16]:
#get the element 4
ser2[3]

/tmp/ipykernel_1207/2448710113.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[3]

np.uint8(4)

In [17]:
#implicity index and explict index of 4-3,d
ser2.iloc[3]

np.uint8(4)

In [18]:
ser2.loc['d']

np.uint8(4)

In [19]:
#get the elements 2,3,4,5_iloc
ser2.iloc[1:5]

b    2
c    3
d    4
e    5
Name: NUM, dtype: uint8

for explict indices end index in inclusive

In [20]:
#get the elements 2,3,4,5_loc
ser2.loc['b':'e']

b    2
c    3
d    4
e    5
Name: NUM, dtype: uint8

In [23]:
#get the elements 2,4,6
ser2.iloc[1::2]

b    2
d    4
f    6
Name: NUM, dtype: uint8

In [24]:
ser2.loc['b':'f':2]

b    2
d    4
f    6
Name: NUM, dtype: uint8

In [25]:
ser2

a    1
b    2
c    3
d    4
e    5
f    6
Name: NUM, dtype: uint8

In [26]:
#get the elements 1,4,5,6
ser2.iloc[[0,3,4,5]]

a    1
d    4
e    5
f    6
Name: NUM, dtype: uint8

In [27]:
ser2.loc[['a','d','e','f']]

a    1
d    4
e    5
f    6
Name: NUM, dtype: uint8

In [ ]:
#get the even elements
ser2.iloc[ser2%2==0]

In [28]:
#get the even elements
ser2.loc[ser2%2==0]

b    2
d    4
f    6
Name: NUM, dtype: uint8

In [31]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [32]:
df=pd.DataFrame(arr,index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4','c5','c6'])
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [33]:
#get element 15 loc & iloc
df.loc['r3','c3']

np.int64(15)

In [34]:
df.iloc[2,2]

np.int64(15)

.at[r1,c1] and .iat[r1,c1]**

-only applicable for indexing(retriviewing

In [35]:
df.at['r3','c3']

np.int64(15)

In [36]:
df.iat[2,2]

np.int64(15)

In [37]:
#get the 3rd column from df
#df.iloc[rRange,cRange]
df.iloc[:,2:3] #dataframe

    c3
r1   3
r2   9
r3  15
r4  21
r5  27

In [42]:
#df.iloc[rRange,cindex]
df.iloc[:,2] #series

r1     3
r2     9
r3    15
r4    21
r5    27
Name: c3, dtype: int64

In [39]:
#get the 3rd column from df
#df.loc[rRange,cRange]
df.loc[:,'c3':'c3'] #dataframe

    c3
r1   3
r2   9
r3  15
r4  21
r5  27

In [43]:
#df.loc[rRange,cindex]
df.loc[:,'c3'] #series

r1     3
r2     9
r3    15
r4    21
r5    27
Name: c3, dtype: int64

a popular way to get single column

-df['column name']-series

--df[['column name']]-dataframe

In [44]:
df['c3']

r1     3
r2     9
r3    15
r4    21
r5    27
Name: c3, dtype: int64

In [45]:
df[['c3']]

    c3
r1   3
r2   9
r3  15
r4  21
r5  27

get row r4

In [46]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [47]:
#df.iloc[rR,cR]
df.iloc[3:4,:]

    c1  c2  c3  c4  c5  c6
r4  19  20  21  22  23  24

In [49]:
#df.iloc[rI,cR]
df.iloc[3,:]

c1    19
c2    20
c3    21
c4    22
c5    23
c6    24
Name: r4, dtype: int64

In [50]:
df.loc['r4':'r4',:]

    c1  c2  c3  c4  c5  c6
r4  19  20  21  22  23  24

In [51]:
df.loc['r4',:] #skip  the column range

c1    19
c2    20
c3    21
c4    22
c5    23
c6    24
Name: r4, dtype: int64

In [52]:
df.iloc[3] #skip the column range

c1    19
c2    20
c3    21
c4    22
c5    23
c6    24
Name: r4, dtype: int64

get column 'c1','c3','c5'

In [53]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [54]:
df.iloc[:,0::2]

    c1  c3  c5
r1   1   3   5
r2   7   9  11
r3  13  15  17
r4  19  21  23
r5  25  27  29

In [55]:
df.loc[:,'c1':'c5':2]

    c1  c3  c5
r1   1   3   5
r2   7   9  11
r3  13  15  17
r4  19  21  23
r5  25  27  29

In [56]:
df[['c1','c3','c5']]

    c1  c3  c5
r1   1   3   5
r2   7   9  11
r3  13  15  17
r4  19  21  23
r5  25  27  29

get brows 'r1','r3',r5

In [57]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [58]:
df.iloc[0::2]

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r3  13  14  15  16  17  18
r5  25  26  27  28  29  30

In [59]:
df.loc['r1':'r5':2]

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r3  13  14  15  16  17  18
r5  25  26  27  28  29  30

get the columns 'c2','c5','c3' in the same order

In [60]:
df[['c2','c5','c3']]

    c2  c5  c3
r1   2   5   3
r2   8  11   9
r3  14  17  15
r4  20  23  21
r5  26  29  27

In [61]:
df.iloc[:,[1,4,2]]

    c2  c5  c3
r1   2   5   3
r2   8  11   9
r3  14  17  15
r4  20  23  21
r5  26  29  27

In [63]:
df.loc[:,['c2','c5','c3']]

    c2  c5  c3
r1   2   5   3
r2   8  11   9
r3  14  17  15
r4  20  23  21
r5  26  29  27

get the r1,r5,r3 in the same order

In [64]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [65]:
df.iloc[[0,4,2]]

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r5  25  26  27  28  29  30
r3  13  14  15  16  17  18

In [66]:
df.loc[['r1','r5','r3']]

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r5  25  26  27  28  29  30
r3  13  14  15  16  17  18

In [67]:
#use booleans and get the columns c2,c4 and c6
df.loc[:,[False,True,False,True,False,True]]

    c2  c4  c6
r1   2   4   6
r2   8  10  12
r3  14  16  18
r4  20  22  24
r5  26  28  30

use booleans and get rows r1,r3,r5

In [69]:
df.loc[[True,False,True,False,True]]

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r3  13  14  15  16  17  18
r5  25  26  27  28  29  30

In [70]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

**by applying condition on a row-COLUMN BOOLEANS

-Through 'column boolean'-filter the coulmn

In [72]:
#get the columns based on row1 with value>3
df.loc['r1']>3 #column booleans

c1    False
c2    False
c3    False
c4     True
c5     True
c6     True
Name: r1, dtype: bool

Df.loc[rI/rR/rl/rB,cI/cR/cL/**cB**]

In [73]:
df.loc[:,df.loc['r1']>3]

    c4  c5  c6
r1   4   5   6
r2  10  11  12
r3  16  17  18
r4  22  23  24
r5  28  29  30

get the columns, by applying condition on 'r3 odd numbers

In [74]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

get the rows based ob 'c3 elements >10

In [76]:
df

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   7   8   9  10  11  12
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [77]:
df['c3']>10

r1    False
r2    False
r3     True
r4     True
r5     True
Name: c3, dtype: bool

** by applying condition on columns-row booleans**

-through row Booleans-filter Rows

In [78]:
df.loc[df['c3']>10,:]

    c1  c2  c3  c4  c5  c6
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

In [79]:
df[df['c3']>10] #easy way

    c1  c2  c3  c4  c5  c6
r3  13  14  15  16  17  18
r4  19  20  21  22  23  24
r5  25  26  27  28  29  30

To filter columns(RARE)

-apply condition on ROWS-COLUMNS BOOLEANS

-df.loc[:,COLUMNS BOOLEAN (condition on row)]

To filter ROWS (FREQUENT)

--Aplly condition on column-ROW BOOLEAN

-df.loc[ROW BOOLEAN(condition on column),:]0r

-df[ROW BOOLEAN(condition on column),:]